### ISSUE TITLE
Any way to remove an existing node?

### ISSUE THREAD

**Issue by ctessier** [hardillb/d3-MQTT-Topic-Tree#4]
Hi,

I wanted to know if there is any easy way to remove an existing node from the topic string?

Thank you for your work and your help.
Kind regards,

**Comment by hardillb** [comment]
No, the current code doesn't have a way to remove topic elements. But when would you want to do this? The only time I could see it being of use would be if a null payload was published.

This would require keeping a count on each "node" in the tree of how many topics pass through it to prevent removing nodes that occur in multiple topics
