### ISSUE TITLE
how does this work?

### ISSUE THREAD

**Issue by mgiaco** [hardillb/d3-MQTT-Topic-Tree#5]
Hello,
So I came from the embedded side - my knowledge about js and the web programming really bad. I will fix this in the future I hope :-).  So please can you help me a little bit... how can I run this? I am running OpenHAB and a mosquitto on a pi. So how can I add this to visualize the topics? I cloned it and run the index.html but I didn´t found out how to set the IP.

thanks

**Comment by hardillb** [comment]
Hint: document.location.hostname and document.port get you the host and port the page was loaded from

**Comment by mgiaco** [comment]
So I load this on the PI where the mosquitto is running.
